name: CI
on:
  push:
    # branches:
    # - main
    tags:
      - v*

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          version: ${{ env.VERSION }}
          release: true
          body: |
            <a target="_blank" href="https://apps.apple.com/app/create-custom-symbols/id6476924627" title="Create Custom Symbols AppStore">
              <img alt="Create Custom Symbols AppStore" src="https://jaywcjlove.github.io/sb/download/macos.svg" height="51" />
            </a>

      - name: Create idoc config.
        if: steps.create_tag.outputs.successful == 'true'
        run: |
          cat > idoc.yml << EOF
          site: "Iconize Folder {{version:${{steps.create_tag.outputs.version}}}}"
          keywords: Folder,FolderIcon,IconizeFolder,Icon
          favicon: assets/logo.png
          logo: ./assets/logo.png
          openSource: https://github.com/jaywcjlove/IconizeFolder
          tocs: false
          element: 
            wrapper: style=max-width:720px;
          menus:
            Home: index.html
            Apps: https://wangchujiang.com/#/app
            About: https://wangchujiang.com/#/about
          sideEffectFiles:
            - README.md
            - README.zh.md
            - terms-of-service.md
            - feedback.md
            - feedback.zh.md
            - terms-of-service.zh.md
            - privacy-policy.md
            - privacy-policy.zh.md
          footer: |
            <a href="https://wangchujiang.com/#/app" target="_blank">App</a> • 
            <a href="https://wangchujiang.com/#/projects" target="_blank">Projects</a> • 
            <a href="https://wangchujiang.com/#/sponsor" target="_blank">Sponsor</a> • 
            <a href="https://wangchujiang.com/DevHub/" target="_blank">DevHub</a> • 
            <a href="https://wangchujiang.com/#/app" target="_blank">More Apps</a><br /><br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}          
          EOF

      - run: npm install idoc@1 -g
      - run: idoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist